name: Generate Snake

on:
  push:
    branches:
      - master  # ou a branch que você está usando
  schedule:
    - cron: "0 0 * * *"  # executa uma vez por dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Snake Game
      uses: Platane/snk@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        output: dist/github-snake.svg
        grid_size: 7
        color: "#58A6FF"

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add dist/github-snake.svg
        git commit -m 'Update snake game'
        git push
